/**
 * MCP Server Generator
 * Generates a Model Context Protocol server from agent config
 */

const fs = require('fs');
const path = require('path');

function generateMCP(config, outDir) {
  const mcpDir = path.join(outDir, 'mcp');
  fs.mkdirSync(mcpDir, { recursive: true });

  const tools = (config.tools || []).map(t => {
    const name = typeof t === 'string' ? t : t.name;
    const desc = typeof t === 'string' ? `${name} tool` : (t.description || `${name} tool`);
    const params = typeof t === 'object' && t.parameters ? t.parameters : { type: 'object', properties: {} };
    return { name, description: desc, parameters: params };
  });

  // Default tools if none specified
  if (tools.length === 0) {
    tools.push({
      name: 'hello',
      description: 'Say hello',
      parameters: {
        type: 'object',
        properties: {
          name: { type: 'string', description: 'Name to greet' }
        }
      }
    });
  }

  // Generate server.js
  const serverCode = `/**
 * MCP Server for ${config.name}
 * Generated by @pickaxe/agent-scaffold
 * 
 * Protocol: Model Context Protocol (MCP)
 * Transport: stdio
 */

const { Server } = require('@modelcontextprotocol/sdk/server/index.js');
const { StdioServerTransport } = require('@modelcontextprotocol/sdk/server/stdio.js');
const {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} = require('@modelcontextprotocol/sdk/types.js');

const server = new Server(
  {
    name: "${config.name}",
    version: "${config.version}",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Tool definitions
const TOOLS = ${JSON.stringify(tools, null, 2)};

// Tool handler — implement your logic here
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: TOOLS,
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  
  switch (name) {
${tools.map(t => `    case "${t.name}":
      return {
        content: [
          {
            type: "text",
            text: \`[${config.name}] ${t.description} — args: \${JSON.stringify(args)}\`,
          },
        ],
      };`).join('\n')}
    default:
      return {
        content: [{ type: "text", text: \`Unknown tool: \${name}\` }],
        isError: true,
      };
  }
});

// Start server
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("${config.name} MCP Server running on stdio");
}

main().catch(console.error);
`;

  fs.writeFileSync(path.join(mcpDir, 'server.js'), serverCode);

  // Generate package.json
  const pkg = {
    name: `${config.name}-mcp-server`,
    version: config.version,
    description: `MCP Server for ${config.name}`,
    main: 'server.js',
    scripts: { start: 'node server.js' },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0'
    }
  };
  fs.writeFileSync(path.join(mcpDir, 'package.json'), JSON.stringify(pkg, null, 2));

  // Generate README
  const readme = `# ${config.name} — MCP Server

Generated by @pickaxe/agent-scaffold

## Install
\`\`\`bash
npm install
\`\`\`

## Run
\`\`\`bash
npm start
\`\`\`

## Tools
${tools.map(t => `- **${t.name}**: ${t.description}`).join('\n')}

## Use with Claude Desktop
Add to \`claude_desktop_config.json\`:
\`\`\`json
{
  "mcpServers": {
    "${config.name}": {
      "command": "node",
      "args": ["${path.resolve(mcpDir, 'server.js')}"]
    }
  }
}
\`\`\`
`;
  fs.writeFileSync(path.join(mcpDir, 'README.md'), readme);

  console.log(`  📦 MCP Server → ${mcpDir}/`);
  console.log(`     server.js, package.json, README.md`);
}

module.exports = { generateMCP };
